### PR TITLE
Add provision of immediate Board approval

### PR DESCRIPTION
**Pull request by ThomasGaubert**
Adds provision to purchase proposal process which allows the Board to immediately approve purchases.

### CODE REVIEW

**Comment by zaldaroga** [comment]
Can the general membership at least be notified through Slack?

**Comment by ThomasGaubert** [comment]
@zaldaroga My bad, this is something (along with the entire process, really) that'll be talked about in one of the next GMs. It's nothing that's taking effect until it gets discussed further with the general membership, it's only here to keep note of it. The OM notes from tonight reflect this.

**Review by DrewRomanyk — APPROVED** [review]
Since this is already quasi how it is in the current bylaws, i see no issue with merging this especially when all of this will be merged into the bylaws soon pending officer and general membership approval

**Comment by ThomasGaubert** [comment]
#7 incorporates these changes, so this PR is no longer needed.

**Pull request closed without merging**
