### PR TITLE
Bylaws: Modify Officer Qualifications

### PR DESCRIPTION
**Pull request by DrewRomanyk**
*** THIS HAS NOT BEEN APPROVAL BY BOARD AND GENERAL, DO NOT MERGE ***

The previous qualifications were ambiguous enough to let any Board position to be filled by an active who was just initiated, which is not wanted by the current Board.

*** HAS BEEN APPROVED BY BOARD ***

### CODE REVIEW

**Comment by DrewRomanyk** [comment]
This will handle #12

**Comment by arrdem** [comment]
👍 this is one of those things we always kinda wanted to do but didn't have the history / headcount for.

**Comment by aaaanderson** [comment]
"current members" should be either "current active members at the time of election by the General Membership or nomination by their reporting Officer" or "current initiated members"

basically it's ambiguous right now as I read it

**Comment by aaaanderson** [comment]
Phrasing for the update is a bit ungrammatical.

The lengthy trailing clause was just to specify at what point in time they must be active (elections vs. term of service). Maybe it's not necessary at all.

**Pull request merged**
