### PR TITLE
including minor senior advice

### PR DESCRIPTION
**Pull request by aaaanderson**

### CODE REVIEW

**Comment by gregorycerna** [comment]
petition to reopen plz

**Comment by arrdem** [comment]
0dde2380-e50f-417a-8cc2-475056c64bff

**Comment by aaaanderson** [comment]
hmmmmmmmmmmmmmmmm looks like admin abuse to me

**Comment by yg-gd** [comment]
That's a much higher rez seal of a approval than I've ever seen

**Comment by dwetterau** [comment]
I think it's the same as this one? [Link to it on Alpha](http://alpha.dwett.com/image/d5e69748-7f10-4971-95e9-863f756f6aa5) Seal

**Comment by aaaanderson** [comment]
david casually plugging his projects on a very important PR

**Comment by dwetterau** [comment]
That was uploaded many months ago.

**Pull request closed without merging**
